/**
 * @file version.h
 * @brief Automatically generated version
 *
 * @author Domenico Salvagnin dominiqs@gmail.com
 * @author Gioni Mexi gionimexi@gmail.com
 * Copyright 2019 Domenico Salvagnin
 */

#ifndef FP_VERSION_H
#define FP_VERSION_H

const char* FP_VERSION = "2.3";

/**
 * Git branch/commit to be generated by cmake
 */

#define FP_GIT_BRANCH "main"
#define FP_GIT_HASH "6dca472-dirty"

#endif /* FP_VERSION_H */
